name: no_late
description: Dart analyzer plugin that prevents LateInitializationError by enforcing safe late keyword usage for lazy initialization only.
version: 0.1.0
homepage: https://github.com/christianfindlay/no_late
repository: https://github.com/christianfindlay/no_late
issue_tracker: https://github.com/christianfindlay/no_late/issues
documentation: https://github.com/christianfindlay/no_late#readme

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.0.0
  analyzer_plugin: ^0.11.0
  custom_lint_builder: ^0.6.10

dev_dependencies:
  austerity: ^1.2.0
  custom_lint: ^0.6.10
  lints: ^3.0.0
  test: ^1.24.0

topics:
  - dart
  - analyzer
  - lint
  - static-analysis
  - late
  - safety
  - plugin
  - custom-lint

funding:
  - https://github.com/sponsors/christianfindlay

platforms:
  linux:
  macos:
  windows: