name: no_late
description: A Dart analyzer plugin that enforces proper usage of the 'late' keyword for lazy initialization only
version: 1.0.0
homepage: https://github.com/dart-lang/sdk/tree/main/pkg/analyzer_plugin

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.0.0
  analyzer_plugin: ^0.11.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0