name: no_late_plugin
description: Analyzer plugin for no_late rules
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.0.0
  analyzer_plugin: ^0.11.0
  no_late:
    path: ../..
dev_dependencies:
  test: ^1.26.3
