name: test_project
description: Test project for no_late custom lint
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  no_late:
    path: ../

dev_dependencies:
  custom_lint: ^0.6.10
  lints: ^3.0.0
  test: ^1.26.3
